# Generated by Django 4.0.3 on 2022-03-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_home_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='is_active',
            field=models.BooleanField(default=True, null=True, verbose_name='Активен'),
        ),
    ]
